### ISSUE TITLE
Doesn't mark offenses on editor

### ISSUE THREAD

**Issue by michalsapka** [jsmecham/nova-eslint#2]
- the extension console shows found offenses (lots of found offenses)
- the issue sidebar shows offenses on file

however
- the offenses are not marked in the editor
- clicking on an offense, doesn't point the editor to correct place in the file.

I don't see any errors, however the last point: maybe the extension invalidly sets filer on offenses collection?

**Comment by jsmecham** [comment]
I think this might be related to a fix in a more recent beta of Nova. Will be polishing this up this weekend.
